modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/aurilisdev/Blastcraft" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/aurilisdev/Blastcraft" #optional

logoFile="blastcraft.png" #optional

credits="Thanks to all contributors. Brazil lang file by FITFC." #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.nuclearscience]]
modId="electrodynamics"
mandatory=true
versionRange="[0.10,)"
ordering="NONE"
side="BOTH"